// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQxl9LpcYmR8WuYTJejitesPsxaNcFbB0',
    appId: '1:920670201384:web:88c0c44cdc84d04e9a371d',
    messagingSenderId: '920670201384',
    projectId: 'recetasdecocina-6a71a',
    authDomain: 'recetasdecocina-6a71a.firebaseapp.com',
    databaseURL: 'https://recetasdecocina-6a71a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recetasdecocina-6a71a.firebasestorage.app',
    measurementId: 'G-F6ED8RMZ44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOxtp3ttTtElslHu0CrhYOP6e_frKoUBk',
    appId: '1:920670201384:android:8442315a4bf0f9f49a371d',
    messagingSenderId: '920670201384',
    projectId: 'recetasdecocina-6a71a',
    databaseURL: 'https://recetasdecocina-6a71a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recetasdecocina-6a71a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQxl9LpcYmR8WuYTJejitesPsxaNcFbB0',
    appId: '1:920670201384:web:0834ddb79e7810ec9a371d',
    messagingSenderId: '920670201384',
    projectId: 'recetasdecocina-6a71a',
    authDomain: 'recetasdecocina-6a71a.firebaseapp.com',
    databaseURL: 'https://recetasdecocina-6a71a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recetasdecocina-6a71a.firebasestorage.app',
    measurementId: 'G-YH9S46T7VE',
  );
}
