name: recetasdecocina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  firebase_database: ^11.3.1
  firebase_messaging: ^15.2.1
  google_sign_in: ^6.2.2
  url_launcher: ^6.0.20

  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: